version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo Entering install phase...
      - echo Updating gradle
      - apt-get update gradle
  build:
    commands:
      - echo bulding using Gradle on `date`
      - gradle build
artifacts:
  files:
    - 'build/libs/*.jar'
