version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo nothing to install... proceding to pre-build phase
  pre_build:
    commands: 
      - echo login to ECR
      - aws ecr get-login-password --region $AWS_REGION
  build:
    commands:
      - echo building using Gradle on `date`
      - sh gradlew build
      - echo building docker image
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - docker build -t $ECR_REPO_NAME:latest .
      - docker tag $ECR_REPO_NAME:$IMAGE_TAG $ECR_REPO:$IMAGE_TAG
  post_build: 
    commands:
      - echo the region is $AWS_REGION
      - echo docker image with tag $IMAGE_TAG will be sent to $ECR_REPO
      - docker push $ECR_REPO:$IMAGE_TAG
artifacts:
  files:
    - 'build/libs/*.jar'
