version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - sudo add-apt-repository ppa:cwchien/gradle
      - apt-get update
      - apt-get install gradle
  build:
    commands:
      - echo bulding using Gradle on `date`
      - gradle build
artifacts:
  files:
    - 'build/libs/*.jar'
